import './globals.css';
import Link from 'next/link';
import { Fira_Sans } from 'next/font/google';
import { ThemeProvider } from '@/providers/ThemeProvider';
import { ThemeToggle } from '@/components/ThemeToggle';
import { cn } from '@/lib/utils';
import Copyright from '@/components/Copyright';
import Logo from '@/components/Logo';
import Navigation from '@/components/Navigation';
import Header from '@/components/Header';

const fira = Fira_Sans({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(
          fira.className,
          'antialiased min-h-screen',
          'bg-zinc-300 dark:bg-zinc-900 text-zinc-600 dark:text-zinc-400',
          'transition-colors duration-500 ease-out'
        )}
      >
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <Header />
          <div className='flex min-h-screen items-center max-w-2xl md:max-w-3xl ml-0 p-4 md:p-8'>
            <main>{children}</main>
          </div>
          <Copyright rotate />
        </ThemeProvider>
      </body>
    </html>
  );
}
