import './globals.css';
import Link from 'next/link';
import { Fira_Sans } from 'next/font/google';
import { ThemeProvider } from '@/providers/ThemeProvider';
import { ThemeToggle } from '@/components/ThemeToggle';
import { cn } from '@/lib/utils';
import Copyright from '@/components/Copyright';
import Logo from '@/components/Logo';

const fira = Fira_Sans({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(
          fira.className,
          'antialiased min-h-screen',
          'bg-zinc-300 dark:bg-zinc-900 text-zinc-600 dark:text-zinc-400',
          'transition-colors duration-500 ease-out'
        )}
      >
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <div className='max-w-2xl mx-auto py-10 px-4'>
            <header className='flex items-center justify-between'>
              <Logo color='#666666' />
              <nav className='flex items-center ml-auto text-sm font-medium space-x-6'>
                <Link href='/about'>About</Link>
                <Link href='/works'>Works</Link>
                <Link href='/contact'>Contact</Link>
                <ThemeToggle />
              </nav>
            </header>
            <main>{children}</main>
            <Copyright />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
